# ==========================
# setup-booking.ps1
# ==========================
# This script:
# - Adds Flyway + validation dependency if missing
# - Writes application.properties with ddl-auto=validate
# - Writes Flyway migrations (V1 init, V2 seed)
# - Writes/overwrites Java code for booking service (entities, repos, service, controller, handler)
# - Resets local H2 file db (./data/bookingdb*)
# - Builds the project

param()

function Write-Utf8NoBom([string]$path, [string]$content) {
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
}

function Backup-File([string]$path, [string]$backupDir) {
  if (Test-Path $path) {
    $name = Split-Path $path -Leaf
    Copy-Item $path (Join-Path $backupDir $name) -Force
  }
}

# ---------- Safety: backup ----------
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backupDir = Join-Path (Get-Location) ("_backup_" + $timestamp)
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null

Backup-File ".\pom.xml" $backupDir
if (Test-Path ".\src\main\resources\application.properties") { Backup-File ".\src\main\resources\application.properties" $backupDir }
if (Test-Path ".\src\main\resources\application.yml") { Backup-File ".\src\main\resources\application.yml" $backupDir }

Write-Host "Backup created at: $backupDir"

# ---------- Check duplicates ----------
$dupes = Get-ChildItem .\src\main\java -Recurse -File -Filter "Booking.java" | Select-Object -ExpandProperty FullName
if ($dupes.Count -gt 1) {
  Write-Host "WARNING: Multiple Booking.java files found:" -ForegroundColor Yellow
  $dupes | ForEach-Object { Write-Host " - $_" -ForegroundColor Yellow }
  Write-Host "Stop and delete duplicates first. Exiting." -ForegroundColor Yellow
  exit 1
}

# ---------- Patch pom.xml (add Flyway + Validation if missing) ----------
$pomPath = ".\pom.xml"
if (!(Test-Path $pomPath)) { throw "pom.xml not found at $pomPath" }

$pom = Get-Content $pomPath -Raw

function Ensure-Dependency([string]$xml, [string]$artifactId, [string]$dependencyXml) {
  if ($xml -match "<artifactId>$artifactId</artifactId>") { return $xml }
  return ($xml -replace "(</dependencies>)", ($dependencyXml + "`r`n  `$1"))
}

$flywayDep = @"
  <dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-core</artifactId>
  </dependency>
"@

$validationDep = @"
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
  </dependency>
"@

$pom2 = $pom
$pom2 = Ensure-Dependency $pom2 "flyway-core" $flywayDep
$pom2 = Ensure-Dependency $pom2 "spring-boot-starter-validation" $validationDep

if ($pom2 -ne $pom) {
  Write-Utf8NoBom $pomPath $pom2
  Write-Host "pom.xml patched (Flyway + Validation ensured)."
} else {
  Write-Host "pom.xml already has Flyway + Validation."
}

# ---------- Write application.properties ----------
New-Item -ItemType Directory -Force -Path ".\src\main\resources" | Out-Null

$appProps = @"
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/bookingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Stop Hibernate from changing schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway is source of truth
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
"@

Write-Utf8NoBom ".\src\main\resources\application.properties" $appProps
Write-Host "application.properties written."

# ---------- Flyway migrations ----------
New-Item -ItemType Directory -Force -Path ".\src\main\resources\db\migration" | Out-Null

$V1 = @"
CREATE TABLE RESOURCES (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  timezone VARCHAR(64) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE BOOKINGS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT NOT NULL,
  customer_name VARCHAR(200) NOT NULL,
  start_at TIMESTAMP WITH TIME ZONE NOT NULL,
  end_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_bookings_resource FOREIGN KEY (resource_id) REFERENCES RESOURCES(id)
);

CREATE INDEX idx_bookings_resource_time ON BOOKINGS(resource_id, start_at, end_at);

CREATE TABLE BOOKING_SLOTS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  resource_id BIGINT NOT NULL,
  slot_start_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_slots_booking FOREIGN KEY (booking_id) REFERENCES BOOKINGS(id) ON DELETE CASCADE,
  CONSTRAINT fk_slots_resource FOREIGN KEY (resource_id) REFERENCES RESOURCES(id),
  CONSTRAINT uq_resource_slot_start UNIQUE (resource_id, slot_start_at)
);

CREATE INDEX idx_slots_resource_start ON BOOKING_SLOTS(resource_id, slot_start_at);
"@

$V2 = @"
INSERT INTO RESOURCES(name, timezone, created_at)
VALUES ('Room A', 'Africa/Casablanca', CURRENT_TIMESTAMP);
"@

Write-Utf8NoBom ".\src\main\resources\db\migration\V1__init.sql" $V1
Write-Utf8NoBom ".\src\main\resources\db\migration\V2__seed.sql" $V2
Write-Host "Flyway migrations written."

# ---------- Java code ----------
New-Item -ItemType Directory -Force -Path ".\src\main\java\com\booking\domain" | Out-Null
New-Item -ItemType Directory -Force -Path ".\src\main\java\com\booking\service" | Out-Null

$BookingStatus = @"
package com.booking.domain;

public enum BookingStatus {
    CONFIRMED,
    CANCELED
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\domain\BookingStatus.java" $BookingStatus

$Resource = @"
package com.booking.domain;

import jakarta.persistence.*;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

@Entity
@Table(name = "RESOURCES")
public class Resource {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable=false, length=200)
    private String name;

    @Column(nullable=false, length=64)
    private String timezone;

    @Column(name="created_at", nullable=false)
    private OffsetDateTime createdAt;

    protected Resource() {}

    @PrePersist
    void prePersist() {
        this.createdAt = OffsetDateTime.now(ZoneOffset.UTC);
    }

    public Long getId() { return id; }
    public String getName() { return name; }
    public String getTimezone() { return timezone; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\domain\Resource.java" $Resource

$Booking = @"
package com.booking.domain;

import jakarta.persistence.*;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

@Entity
@Table(name = "BOOKINGS")
public class Booking {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name="resource_id", nullable=false)
    private Long resourceId;

    @Column(name="customer_name", nullable=false, length=200)
    private String customerName;

    @Column(name="start_at", nullable=false)
    private OffsetDateTime startAt;

    @Column(name="end_at", nullable=false)
    private OffsetDateTime endAt;

    @Enumerated(EnumType.STRING)
    @Column(name="status", nullable=false, length=20)
    private BookingStatus status;

    @Column(name="created_at", nullable=false)
    private OffsetDateTime createdAt;

    @Column(name="updated_at", nullable=false)
    private OffsetDateTime updatedAt;

    protected Booking() {}

    public Booking(Long resourceId, String customerName, OffsetDateTime startAt, OffsetDateTime endAt) {
        this.resourceId = resourceId;
        this.customerName = customerName;
        this.startAt = startAt;
        this.endAt = endAt;
        this.status = BookingStatus.CONFIRMED;
    }

    @PrePersist
    void prePersist() {
        OffsetDateTime now = OffsetDateTime.now(ZoneOffset.UTC);
        this.createdAt = now;
        this.updatedAt = now;
        if (this.status == null) this.status = BookingStatus.CONFIRMED;
    }

    @PreUpdate
    void preUpdate() {
        this.updatedAt = OffsetDateTime.now(ZoneOffset.UTC);
    }

    public Long getId() { return id; }
    public Long getResourceId() { return resourceId; }
    public String getCustomerName() { return customerName; }
    public OffsetDateTime getStartAt() { return startAt; }
    public OffsetDateTime getEndAt() { return endAt; }
    public BookingStatus getStatus() { return status; }
    public void setStatus(BookingStatus status) { this.status = status; }
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\domain\Booking.java" $Booking

$BookingSlot = @"
package com.booking.domain;

import jakarta.persistence.*;
import java.time.OffsetDateTime;

@Entity
@Table(
    name = "BOOKING_SLOTS",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_resource_slot_start",
        columnNames = {"resource_id", "slot_start_at"}
    )
)
public class BookingSlot {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "resource_id", nullable = false)
    private Long resourceId;

    @Column(name = "slot_start_at", nullable = false)
    private OffsetDateTime slotStartAt;

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", nullable = false)
    private Booking booking;

    protected BookingSlot() {}

    public BookingSlot(Long resourceId, OffsetDateTime slotStartAt, Booking booking) {
        this.resourceId = resourceId;
        this.slotStartAt = slotStartAt;
        this.booking = booking;
    }

    public Long getId() { return id; }
    public Long getResourceId() { return resourceId; }
    public OffsetDateTime getSlotStartAt() { return slotStartAt; }
    public Booking getBooking() { return booking; }
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\domain\BookingSlot.java" $BookingSlot

$BookingRepo = @"
package com.booking;

import com.booking.domain.Booking;
import org.springframework.data.jpa.repository.JpaRepository;

public interface BookingRepository extends JpaRepository<Booking, Long> {
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\BookingRepository.java" $BookingRepo

$SlotRepo = @"
package com.booking;

import com.booking.domain.BookingSlot;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.OffsetDateTime;
import java.util.List;

public interface BookingSlotRepository extends JpaRepository<BookingSlot, Long> {

    @Query("""
        select s.slotStartAt
        from BookingSlot s
        where s.resourceId = :resourceId
          and s.slotStartAt >= :from
          and s.slotStartAt < :to
    """)
    List<OffsetDateTime> findBookedSlotStarts(
            @Param("resourceId") Long resourceId,
            @Param("from") OffsetDateTime from,
            @Param("to") OffsetDateTime to
    );

    @Modifying
    @Query("delete from BookingSlot s where s.booking.id = :bookingId")
    int deleteByBookingId(@Param("bookingId") Long bookingId);
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\BookingSlotRepository.java" $SlotRepo

$ResourceRepo = @"
package com.booking;

import com.booking.domain.Resource;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ResourceRepository extends JpaRepository<Resource, Long> {
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\ResourceRepository.java" $ResourceRepo

$Service = @"
package com.booking.service;

import com.booking.*;
import com.booking.domain.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.*;

@Service
public class BookingService {

    private static final int SLOT_MINUTES = 15;

    private final BookingRepository bookingRepository;
    private final BookingSlotRepository bookingSlotRepository;
    private final ResourceRepository resourceRepository;

    public BookingService(BookingRepository bookingRepository,
                          BookingSlotRepository bookingSlotRepository,
                          ResourceRepository resourceRepository) {
        this.bookingRepository = bookingRepository;
        this.bookingSlotRepository = bookingSlotRepository;
        this.resourceRepository = resourceRepository;
    }

    public record CreateBookingRequest(Long resourceId, String customerName, OffsetDateTime startAt, OffsetDateTime endAt) {}
    public record CreateBookingResponse(Long bookingId, BookingStatus status) {}
    public record AvailabilityResponse(Long resourceId, OffsetDateTime from, OffsetDateTime to, int slotMinutes, List<OffsetDateTime> freeSlots) {}

    @Transactional
    public CreateBookingResponse createBooking(CreateBookingRequest req) {
        if (req.resourceId() == null) throw new IllegalArgumentException("resourceId is required");
        if (req.customerName() == null || req.customerName().isBlank()) throw new IllegalArgumentException("customerName is required");
        if (req.startAt() == null || req.endAt() == null) throw new IllegalArgumentException("startAt and endAt are required");

        resourceRepository.findById(req.resourceId()).orElseThrow(() -> new NotFoundException("Resource not found: " + req.resourceId()));

        OffsetDateTime startUtc = req.startAt().withOffsetSameInstant(ZoneOffset.UTC);
        OffsetDateTime endUtc   = req.endAt().withOffsetSameInstant(ZoneOffset.UTC);

        if (!startUtc.isBefore(endUtc)) throw new IllegalArgumentException("startAt must be before endAt");

        long minutes = Duration.between(startUtc, endUtc).toMinutes();
        if (minutes <= 0 || minutes % SLOT_MINUTES != 0) {
            throw new IllegalArgumentException("Duration must be a positive multiple of 15 minutes");
        }

        Booking booking = new Booking(req.resourceId(), req.customerName().trim(), startUtc, endUtc);
        booking = bookingRepository.save(booking);

        List<BookingSlot> slots = new ArrayList<>();
        OffsetDateTime cursor = startUtc;
        while (cursor.isBefore(endUtc)) {
            slots.add(new BookingSlot(req.resourceId(), cursor, booking));
            cursor = cursor.plusMinutes(SLOT_MINUTES);
        }

        try {
            bookingSlotRepository.saveAll(slots);
            bookingSlotRepository.flush(); // force unique constraint check now
        } catch (DataIntegrityViolationException ex) {
            throw new ConflictException("Time slot already booked for this resource");
        }

        return new CreateBookingResponse(booking.getId(), booking.getStatus());
    }

    @Transactional(readOnly = true)
    public AvailabilityResponse getAvailability(Long resourceId, OffsetDateTime from, OffsetDateTime to) {
        if (resourceId == null) throw new IllegalArgumentException("resourceId is required");
        if (from == null || to == null) throw new IllegalArgumentException("from and to are required");

        resourceRepository.findById(resourceId).orElseThrow(() -> new NotFoundException("Resource not found: " + resourceId));

        OffsetDateTime fromUtc = from.withOffsetSameInstant(ZoneOffset.UTC);
        OffsetDateTime toUtc   = to.withOffsetSameInstant(ZoneOffset.UTC);
        if (!fromUtc.isBefore(toUtc)) throw new IllegalArgumentException("from must be before to");

        List<OffsetDateTime> all = new ArrayList<>();
        OffsetDateTime cursor = fromUtc;
        while (cursor.isBefore(toUtc)) {
            all.add(cursor);
            cursor = cursor.plusMinutes(SLOT_MINUTES);
        }

        List<OffsetDateTime> booked = bookingSlotRepository.findBookedSlotStarts(resourceId, fromUtc, toUtc);
        Set<OffsetDateTime> bookedSet = new HashSet<>(booked);

        List<OffsetDateTime> free = new ArrayList<>();
        for (OffsetDateTime s : all) if (!bookedSet.contains(s)) free.add(s);

        return new AvailabilityResponse(resourceId, fromUtc, toUtc, SLOT_MINUTES, free);
    }

    @Transactional
    public void cancelBooking(Long bookingId) {
        Booking booking = bookingRepository.findById(bookingId)
                .orElseThrow(() -> new NotFoundException("Booking not found: " + bookingId));

        if (booking.getStatus() == BookingStatus.CANCELED) return;

        booking.setStatus(BookingStatus.CANCELED);
        bookingRepository.save(booking);

        // Free slots immediately
        bookingSlotRepository.deleteByBookingId(bookingId);
    }

    public static class ConflictException extends RuntimeException { public ConflictException(String m){ super(m);} }
    public static class NotFoundException extends RuntimeException { public NotFoundException(String m){ super(m);} }
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\service\BookingService.java" $Service

$Controller = @"
package com.booking;

import com.booking.service.BookingService;
import com.booking.service.BookingService.AvailabilityResponse;
import com.booking.service.BookingService.CreateBookingRequest;
import com.booking.service.BookingService.CreateBookingResponse;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.time.OffsetDateTime;

@RestController
@RequestMapping("/api")
public class BookingController {

    private final BookingService bookingService;

    public BookingController(BookingService bookingService) {
        this.bookingService = bookingService;
    }

    public record CreateBookingBody(
            @NotNull Long resourceId,
            @NotBlank String customerName,
            @NotNull OffsetDateTime startAt,
            @NotNull OffsetDateTime endAt
    ) {}

    @PostMapping("/bookings")
    @ResponseStatus(HttpStatus.CREATED)
    public CreateBookingResponse createBooking(@Valid @RequestBody CreateBookingBody body) {
        return bookingService.createBooking(new CreateBookingRequest(
                body.resourceId(), body.customerName(), body.startAt(), body.endAt()
        ));
    }

    @GetMapping("/resources/{resourceId}/availability")
    public AvailabilityResponse availability(
            @PathVariable Long resourceId,
            @RequestParam OffsetDateTime from,
            @RequestParam OffsetDateTime to
    ) {
        return bookingService.getAvailability(resourceId, from, to);
    }

    @PostMapping("/bookings/{bookingId}/cancel")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void cancel(@PathVariable Long bookingId) {
        bookingService.cancelBooking(bookingId);
    }
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\BookingController.java" $Controller

$Errors = @"
package com.booking;

import com.booking.service.BookingService;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.time.OffsetDateTime;
import java.util.Map;

@RestControllerAdvice
public class ApiExceptionHandler {

    @ExceptionHandler(BookingService.NotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public Map<String, Object> notFound(Exception ex) {
        return Map.of(
                "timestamp", OffsetDateTime.now().toString(),
                "error", "NOT_FOUND",
                "message", ex.getMessage()
        );
    }

    @ExceptionHandler(BookingService.ConflictException.class)
    @ResponseStatus(HttpStatus.CONFLICT)
    public Map<String, Object> conflict(Exception ex) {
        return Map.of(
                "timestamp", OffsetDateTime.now().toString(),
                "error", "CONFLICT",
                "message", ex.getMessage()
        );
    }

    @ExceptionHandler(IllegalArgumentException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public Map<String, Object> badRequest(Exception ex) {
        return Map.of(
                "timestamp", OffsetDateTime.now().toString(),
                "error", "BAD_REQUEST",
                "message", ex.getMessage()
        );
    }
}
"@
Write-Utf8NoBom ".\src\main\java\com\booking\ApiExceptionHandler.java" $Errors

Write-Host "Java code written."

# ---------- Reset local H2 file DB ----------
Write-Host "Resetting H2 file DB in .\data ..."
if (Test-Path ".\data") {
  Get-ChildItem .\data -Filter "bookingdb*" -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
} else {
  New-Item -ItemType Directory -Force -Path ".\data" | Out-Null
}
Write-Host "H2 DB reset complete."

# ---------- Build ----------
Write-Host "Running mvnw clean test..."
.\mvnw clean test
if ($LASTEXITCODE -ne 0) { throw "Build failed. Check errors above." }

Write-Host "Setup complete ✅ Now run: .\mvnw spring-boot:run"